/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;
import koneksi.koneksi;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
/**
 *
 * @author Hype
 */
public class Layanan extends javax.swing.JFrame {
  private int harga = 0;
    /**
     * Creates new form Layanan
     */
    public Layanan() {
    initComponents();
    
    lbl_nama.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
lbl_alamat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
lbl_hp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

    loadLayanan();
    txtidtrx.setEditable(false);
    
        if (cb_lyn.getItemCount() > 0) {
        ambilHarga();
    }
        
    autoID(); 
    tampilTabel();
    
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    txttgl.setText(sdf.format(new java.util.Date()));
    }
     private void autoID() {
        try {
            Connection conn = koneksi.getKoneksi();
            String sql = "SELECT MAX(id_transaksi) FROM transaksi";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                String max = rs.getString(1);
                if (max == null) {
                    txtidtrx.setText("TRX001");
                } else {
                    int num = Integer.parseInt(max.substring(3)) + 1;
                    txtidtrx.setText("TRX" + String.format("%03d", num));
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
     
      private void loadLayanan() {
        try {
            Connection conn = koneksi.getKoneksi();
            String sql = "SELECT * FROM layanan";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            cb_lyn.removeAllItems();

            while (rs.next()) {
                cb_lyn.addItem(rs.getString("nama_layanan"));
            }

        } catch (Exception e) {
            System.out.println(e);
        }
      }
        
      
      private void ambilHarga() {
        try {
        if (cb_lyn.getSelectedItem() == null) return;

        Connection conn = koneksi.getKoneksi();
        String sql = "SELECT harga_per_kg FROM layanan WHERE nama_layanan=?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, cb_lyn.getSelectedItem().toString());

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            harga = rs.getInt("harga_per_kg");
        }

    } catch (Exception e) {
        System.out.println(e);
    }
      }
      
         private void hitungTotal() {
        try {
            int berat = Integer.parseInt(txtbrt.getText());
            int total = berat * harga;
            txtttl.setText(String.valueOf(total));
        } catch (Exception e) {
            txtttl.setText("0");
        }
    }
         
             private void tampilTabel() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Tanggal");
        model.addColumn("Pelanggan");
        model.addColumn("Layanan");
        model.addColumn("Berat");
        model.addColumn("Total");

        try {
            Connection conn = koneksi.getKoneksi();
            String sql = "SELECT * FROM transaksi";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_transaksi"),
                    rs.getString("tanggal"),
                    rs.getString("pelanggan"),
                    rs.getString("layanan"),
                    rs.getString("berat"),
                    rs.getString("total")
                });
            }

            jtabel.setModel(model);

        } catch (Exception e) {
            System.out.println(e);
        }
    }



     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cb_lyn = new javax.swing.JComboBox<>();
        txtbrt = new javax.swing.JTextField();
        txtttl = new javax.swing.JTextField();
        txttgl = new javax.swing.JTextField();
        txtplg = new javax.swing.JTextField();
        txtidtrx = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabel = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        lbl_nama = new javax.swing.JLabel();
        lbl_alamat = new javax.swing.JLabel();
        lbl_hp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Transaksi");

        jLabel2.setText("ID Pelanggan");

        jLabel3.setText("Tanggal");

        jLabel4.setText("Jenis Layanan");

        jLabel5.setText("Berat (Kg)");

        jLabel6.setText("Total");

        cb_lyn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_lyn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_lynActionPerformed(evt);
            }
        });

        txtbrt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbrtKeyReleased(evt);
            }
        });

        txttgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttglActionPerformed(evt);
            }
        });

        txtplg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtplgActionPerformed(evt);
            }
        });

        btncari.setText("CARI");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        jtabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtabel);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setText("DATA PELANGGAN");

        lbl_nama.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_nama.setText("Nama");

        lbl_alamat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_alamat.setText("Alamat");

        lbl_hp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_hp.setText("Nomor HP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_hp)
                    .addComponent(lbl_alamat)
                    .addComponent(lbl_nama))
                .addGap(482, 482, 482))
            .addGroup(layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cb_lyn, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtbrt)
                                        .addComponent(txtttl)
                                        .addComponent(txttgl, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addComponent(jLabel7))))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtplg)
                            .addComponent(txtidtrx, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btncari)))
                .addContainerGap(306, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidtrx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtplg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_nama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_alamat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_hp)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_lyn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtbrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtttl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        lbl_nama.getAccessibleContext().setAccessibleName("Nama");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_lynActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_lynActionPerformed
        // TODO add your handling code here:       
        ambilHarga();
        hitungTotal();
    }//GEN-LAST:event_cb_lynActionPerformed

    private void txtbrtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbrtKeyReleased
        // TODO add your handling code here:
        hitungTotal();
    }//GEN-LAST:event_txtbrtKeyReleased

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
     try {
        Connection conn = koneksi.getKoneksi();
        String sql = "SELECT * FROM pelanggan WHERE id_pelanggan = ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, txtplg.getText());

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            // tampilkan ke label
            lbl_nama.setText("Nama : " + rs.getString("nama"));
            lbl_alamat.setText("Alamat : " + rs.getString("alamat"));
            lbl_hp.setText("No HP : " + rs.getString("no_hp"));
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
            
            // kosongkan label
lbl_nama.setText("Nama : -");
lbl_alamat.setText("Alamat : -");
lbl_hp.setText("No HP : -");
        }

    } catch (Exception e) {
        System.out.println(e);
    }
    }//GEN-LAST:event_btncariActionPerformed

    private void txtplgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtplgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtplgActionPerformed

    private void txttglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttglActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Layanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Layanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Layanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Layanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Layanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncari;
    private javax.swing.JComboBox<String> cb_lyn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtabel;
    private javax.swing.JLabel lbl_alamat;
    private javax.swing.JLabel lbl_hp;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JTextField txtbrt;
    private javax.swing.JTextField txtidtrx;
    private javax.swing.JTextField txtplg;
    private javax.swing.JTextField txttgl;
    private javax.swing.JTextField txtttl;
    // End of variables declaration//GEN-END:variables
}
