/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


package login;


/**
 *
 * @author Hype
 */
public class MenuUtama extends javax.swing.JFrame {
public MenuUtama(String username, String role) {
    this.setExtendedState(MAXIMIZED_BOTH);
        initComponents();
        lblWelcome.setBorder(new javax.swing.border.EmptyBorder(10, 10, 10, 10));
        lblWelcome.setText("Selamat Datang, " + username + " (" + role + ")");
        
        
 
        
        // Cek Role untuk membatasi hak akses
        if (role.equals("Kasir")) {
            // Contoh: Kasir tidak boleh buka Form User (Manajemen User)
            btnuser.setEnabled(false); 
            menulprn.setEnabled(false);
        }
    }
    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        menulprn = new javax.swing.JButton();
        btnuser = new javax.swing.JButton();
        btnlayanan = new javax.swing.JButton();
        btnpelanggan1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1614, 11, 111, 577));

        lblWelcome.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(0, 51, 51));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("LAUNDRYKU");
        lblWelcome.setToolTipText("");
        getContentPane().add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 580, 95));

        menulprn.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        menulprn.setText("LAPORAN");
        menulprn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menulprn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menulprnActionPerformed(evt);
            }
        });
        getContentPane().add(menulprn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 210, 60));

        btnuser.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        btnuser.setText("USER");
        btnuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuserActionPerformed(evt);
            }
        });
        getContentPane().add(btnuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 210, 60));

        btnlayanan.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        btnlayanan.setText("LAYANAN");
        btnlayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlayananActionPerformed(evt);
            }
        });
        getContentPane().add(btnlayanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 210, 60));

        btnpelanggan1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        btnpelanggan1.setText("PELANGGAN");
        btnpelanggan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpelanggan1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnpelanggan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 220, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\bglaundryku (2).jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -70, 770, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuserActionPerformed
userform fur = new userform();
        fur.setVisible(true);;// TODO add your handling code here:
    }//GEN-LAST:event_btnuserActionPerformed

    private void menulprnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menulprnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menulprnActionPerformed

    private void btnlayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlayananActionPerformed
        // TODO add your handling code here:
        Layanan lyn = new Layanan();
        lyn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlayananActionPerformed

    private void btnpelanggan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpelanggan1ActionPerformed
        // TODO add your handling code here:
        Pelanggan plg = new Pelanggan();
        plg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnpelanggan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlayanan;
    private javax.swing.JButton btnpelanggan1;
    private javax.swing.JButton btnuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JButton menulprn;
    // End of variables declaration//GEN-END:variables
}
