/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import koneksi.koneksi;
/**
 *
 * @author ASUS
 */
public class Pelanggan extends javax.swing.JFrame {
        private Connection conn = koneksi.getKoneksi();
        private DefaultTableModel tabmode;
    /**
     * Creates new form Pelanggan
     */
    public Pelanggan() {
        initComponents();
        kosong();
        aktif();
        datatable();
        autoID();
        txtid.setEditable(false);  
        txtid.setEnabled(false);      
          // ukuran form
        setSize(650, 700);

    // posisi tengah
        setLocationRelativeTo(null);

    // tidak bisa maximize / resize
        setResizable(false);
    }
protected void aktif(){
    txtid.requestFocus();
} 

protected void kosong(){
    txtnm.setText("");
    txtnotelpon.setText("");
    txtalamat.setText("");
    txtcari.setText("");

}
private void autoID() {
    try {
        String sql = "SELECT MAX(id_pelanggan) FROM pelanggan";
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);

        if (rs.next()) {
            String max = rs.getString(1);

            if (max == null) {
                txtid.setText("PL1");
            } else {
                int num = Integer.parseInt(max.substring(2)) + 1;
                txtid.setText("PL" + num);
            }
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Auto ID gagal: " + e);
    }
}
private void datatable(){
    Object[] Baris = {"ID Pelanggan", "Nama", "No. Telepon", "Alamat"};
    tabmode = new DefaultTableModel(null, Baris);

    String cari = txtcari.getText();

    try {
String sql = "SELECT * FROM pelanggan WHERE id_pelanggan LIKE ? OR nama LIKE ?";
        PreparedStatement stat = conn.prepareStatement(sql);
        stat.setString(1, "%" + cari + "%");
        stat.setString(2, "%" + cari + "%");

        ResultSet hasil = stat.executeQuery();

        while (hasil.next()){
            tabmode.addRow(new Object[]{
                hasil.getString("id_pelanggan"),
                hasil.getString("nama"),
                hasil.getString("no_hp"),
                hasil.getString("alamat")
            });
        }

        tblpelanggan.setModel(tabmode);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "data gagal dipanggil "+e);
    }
}
    
public static void main(String[] args) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new Pelanggan().setVisible(true);
        }
    });
}

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtid = new javax.swing.JTextField();
        txtnm = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Jlabel3 = new javax.swing.JLabel();
        txtalamat = new javax.swing.JTextField();
        Jlabel4 = new javax.swing.JLabel();
        txtnotelpon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblpelanggan = new javax.swing.JTable();
        txtcari = new javax.swing.JTextField();
        bsimpan = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        bcari = new javax.swing.JButton();
        btnKembali = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(630, 670));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 156, -1));

        txtnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnmActionPerformed(evt);
            }
        });
        getContentPane().add(txtnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 240, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 31, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("NAMA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 55, -1));

        Jlabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Jlabel3.setText("ALAMAT");
        getContentPane().add(Jlabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 120, -1));
        getContentPane().add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 240, -1));

        Jlabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Jlabel4.setText("NO TELEPON");
        getContentPane().add(Jlabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        txtnotelpon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnotelponActionPerformed(evt);
            }
        });
        getContentPane().add(txtnotelpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 240, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DATA PELANGGAN");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 450, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("DATA PELANGGAN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        tblpelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblpelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpelangganMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblpelanggan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 570, 230));

        txtcari.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 210, 30));

        bsimpan.setText("SIMPAN");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 110, -1));

        bubah.setText("UBAH");
        bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahActionPerformed(evt);
            }
        });
        getContentPane().add(bubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 100, -1));

        bhapus.setText("HAPUS");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });
        getContentPane().add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 100, -1));

        bbatal.setText("BATAL");
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });
        getContentPane().add(bbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 90, -1));

        bkeluar.setText("KELUAR");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(bkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 100, -1));

        bcari.setText("CARI");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });
        getContentPane().add(bcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 83, 40));

        btnKembali.setText("KEMBALI");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 100, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\Aplikasi-Laundry\\src\\Images\\bg 1.jpg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
String sql = "INSERT INTO pelanggan (id_pelanggan, nama, no_hp, alamat) VALUES (?,?,?,?)";

    if(txtid.getText().isEmpty() || txtnm.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!");
        return;
    }

    try{
        PreparedStatement stat = conn.prepareStatement(sql);

        stat.setString(1, txtid.getText());
        stat.setString(2, txtnm.getText());
        stat.setString(3, txtnotelpon.getText());
        stat.setString(4, txtalamat.getText());

        stat.executeUpdate();

        JOptionPane.showMessageDialog(null, "data berhasil disimpan");

        kosong();
        txtid.requestFocus();

    } catch (SQLException e){
        JOptionPane.showMessageDialog(null, "data gagal disimpan "+e);
    }

    datatable();
    autoID();

     
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
                                   
String sql = "UPDATE pelanggan SET nama=?, no_hp=?, alamat=? WHERE id_pelanggan=?";

    try{

        PreparedStatement stat = conn.prepareStatement(sql);

        stat.setString(1, txtnm.getText());
        stat.setString(2, txtnotelpon.getText());
        stat.setString(3, txtalamat.getText());
        stat.setString(4, txtid.getText());

        stat.executeUpdate();

        JOptionPane.showMessageDialog(null, "data berhasil diubah");

        kosong();
        txtid.requestFocus();

    } catch (SQLException e){
        JOptionPane.showMessageDialog(null, "data gagal diubah " + e);
    }

    datatable();  
 
    }//GEN-LAST:event_bubahActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        // TODO add your handling code here:
           int ok = JOptionPane.showConfirmDialog(null, "Hapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    
    if (ok == JOptionPane.YES_OPTION) {
String sql = "DELETE FROM pelanggan WHERE id_pelanggan=?";

        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtid.getText());
            stat.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            kosong();
            txtid.requestFocus();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data gagal dihapus " + e);
        }

        datatable();
    }
    }//GEN-LAST:event_bhapusActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        // TODO add your handling code here:
        kosong();
        aktif();
        autoID();
            txtnm.requestFocus();
    }//GEN-LAST:event_bbatalActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        // TODO add your handling code here:
       this.dispose();
    }//GEN-LAST:event_bkeluarActionPerformed

    private void tblpelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpelangganMouseClicked
        // TODO add your handling code here:
    int bar = tblpelanggan.getSelectedRow();
    if (bar == -1) return;

    txtid.setText(tabmode.getValueAt(bar, 0).toString());
    txtnm.setText(tabmode.getValueAt(bar, 1).toString());
    txtnotelpon.setText(tabmode.getValueAt(bar, 2).toString());
    txtalamat.setText(tabmode.getValueAt(bar, 3).toString()); 
    }//GEN-LAST:event_tblpelangganMouseClicked

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        String cari = txtcari.getText();

    datatable();
    }//GEN-LAST:event_bcariActionPerformed

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
            datatable();
      
    }//GEN-LAST:event_txtcariActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtnotelponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnotelponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnotelponActionPerformed

    private void txtnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnmActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
         new MenuUtama().setVisible(true); 
         this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlabel3;
    private javax.swing.JLabel Jlabel4;
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bcari;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bsimpan;
    private javax.swing.JToggleButton btnKembali;
    private javax.swing.JButton bubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblpelanggan;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnm;
    private javax.swing.JTextField txtnotelpon;
    // End of variables declaration//GEN-END:variables
}
