/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import javax.swing.JOptionPane;
import java.sql.Statement;

/**
 *
 * @author Hype
 */
public class tmbhlayanan extends javax.swing.JFrame {
    
    
    private void auto_id() {
      try {
        Connection conn = koneksi.getKoneksi();
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery("SELECT id_layanan FROM layanan ORDER BY id_layanan DESC LIMIT 1");

        String id = "LY001"; // default kalau kosong

        if (rs.next()) {
            String lastID = rs.getString("id_layanan");

            if (lastID != null && lastID.length() >= 3) {
                String angka = lastID.substring(2); // ambil angka
                int no = Integer.parseInt(angka) + 1;
                id = "LY" + String.format("%03d", no);
            }
        }

        txtid.setText(id);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "AutoID gagal: " + e.getMessage());
    }
}
    
    private void tampil_data() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("Jenis Layanan");
    model.addColumn("Harga");

    try {
        String sql = "SELECT * FROM layanan";
        Connection conn = koneksi.getKoneksi();
        java.sql.Statement stm = conn.createStatement();
        ResultSet res = stm.executeQuery(sql);

        while (res.next()) {
            model.addRow(new Object[]{
                res.getString("id_layanan"),
                res.getString("nama_layanan"),
                res.getString("harga_per_kg")
            });
        }

        jtabel.setModel(model);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal tampil data: " + e.getMessage());
    }
}

    /**
     * Creates new form tmbhlayanan
     */
    public tmbhlayanan() {
        initComponents();
        tampil_data();
        auto_id();
        txtid.setEditable(false); 
         setLocationRelativeTo(null);

    // tidak bisa maximize / resize
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtjenis = new javax.swing.JTextField();
        txthrg = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnmenu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtabel = new javax.swing.JTable();
        txtid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(860, 620));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setText("TAMBAH LAYANAN");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 527, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Jenis Layanan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Harga Layanan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));
        getContentPane().add(txtjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 240, -1));
        getContentPane().add(txthrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 240, -1));

        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        btnubah.setText("UBAH");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });
        getContentPane().add(btnubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 97, -1));

        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 109, -1));

        btnmenu.setText("MENU");
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 125, -1));

        jtabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtabel);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 618, 160));
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 240, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("ID Layanan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\Aplikasi-Laundry\\src\\Images\\bg 1.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
          try {
        if (txtjenis.getText().isEmpty() || txthrg.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!");
        return;
}
        int harga = Integer.parseInt(txthrg.getText());
        String sql = "INSERT INTO layanan (id_layanan, nama_layanan, harga_per_kg) VALUES (?,?,?)";

        Connection conn = koneksi.getKoneksi();
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, txtid.getText());
        pst.setString(2, txtjenis.getText());
        pst.setString(3, txthrg.getText());

        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
        tampil_data();
        txtjenis.setText("");
        txthrg.setText("");
        auto_id();

        txtjenis.setText("");
        txthrg.setText("");

} catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal simpan: " + e.getMessage());
    }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void jtabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabelMouseClicked
        // TODO add your handling code here:
    int baris = jtabel.rowAtPoint(evt.getPoint());

    txtid.setText(jtabel.getValueAt(baris, 0).toString());
    txtjenis.setText(jtabel.getValueAt(baris, 1).toString());
    txthrg.setText(jtabel.getValueAt(baris, 2).toString());
    }//GEN-LAST:event_jtabelMouseClicked

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        // TODO add your handling code here:
           try {
               
        int baris = jtabel.getSelectedRow();
        if (baris == -1) {
        JOptionPane.showMessageDialog(null, "Pilih data dulu!");
        return;
}
        String id = jtabel.getValueAt(baris, 0).toString();

        String sql = "UPDATE layanan SET nama_layanan=?, harga_per_kg=? WHERE id_layanan=?";
        Connection conn = koneksi.getKoneksi();
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, txtjenis.getText());
        pst.setString(2, txthrg.getText());
        pst.setString(3, id);

        pst.executeUpdate();

        JOptionPane.showMessageDialog(null, "Data berhasil diubah");

        tampil_data();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal ubah: " + e.getMessage());
    }
        
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
         try {
        int baris = jtabel.getSelectedRow();
        if (baris == -1) {
        JOptionPane.showMessageDialog(null, "Pilih data dulu!");
        return;
}
        String id = jtabel.getValueAt(baris, 0).toString();

        String sql = "DELETE FROM layanan WHERE id_layanan=?";
        Connection conn = koneksi.getKoneksi();
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, id);
        pst.executeUpdate();

        JOptionPane.showMessageDialog(null, "Data berhasil dihapus");

        tampil_data();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal hapus: " + e.getMessage());
    }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        // TODO add your handling code here:
    new MenuUtama().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tmbhlayanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tmbhlayanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tmbhlayanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tmbhlayanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tmbhlayanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jtabel;
    private javax.swing.JTextField txthrg;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtjenis;
    // End of variables declaration//GEN-END:variables
}
