/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transaksi;
import koneksi.koneksi;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ASUS
 */
public class pembayaran extends javax.swing.JFrame {
private String namaAsli = "";


    /**
     * Creates new form pembayaran
     */
    public pembayaran() {
        initComponents();

    autoIDBayar();

    

    cbStatus.addItem("Lunas");
    cbStatus.addItem("Belum Lunas");
    txtIdPembayaran.setEditable(false);
    txtTotalBayar.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtIdPembayaran = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtIdTransaksi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTotalBayar = new javax.swing.JTextField();
        cbStatus = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        bsimpan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PEMBAYARAN");
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 498, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("ID Pembayaran");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 87, -1, -1));
        getContentPane().add(txtIdPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 85, 122, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("ID Transaksi");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 114, -1, -1));

        txtIdTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdTransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 112, 122, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Total");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 143, -1, -1));

        txtTotalBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalBayarActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotalBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 145, 122, -1));

        cbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStatusActionPerformed(evt);
            }
        });
        getContentPane().add(cbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 173, 122, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Status");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 171, -1, -1));

        bsimpan.setText("SIMPAN");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 215, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\Aplikasi-Laundry\\src\\Images\\bg 1.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setData(String idTransaksi, String totalBayar) {

    txtIdTransaksi.setText(idTransaksi);

    // validasi null
    if (totalBayar == null || totalBayar.equals("")) {

        txtTotalBayar.setText("0");

    } else {

        // hapus .0 jika ada
        txtTotalBayar.setText(
                totalBayar.replace(".0", "")
        );
    }
}
   private void autoIDBayar() {

    try {

        Connection conn = koneksi.getKoneksi();

        String sql = "SELECT MAX(id_pembayaran) FROM pembayaran";

        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);

        if (rs.next()) {

            String max = rs.getString(1);

            if (max == null) {

                txtIdPembayaran.setText("BYR001");

            } else {

                int num =
                        Integer.parseInt(max.substring(3)) + 1;

                txtIdPembayaran.setText(
                        "BYR" + String.format("%03d", num));
            }
        }

    } catch (Exception e) {
        System.out.println(e);
    }
}
   
private void ambilNamaPelanggan() {

    try {

        Connection conn = koneksi.getKoneksi();

        String sql =
            "SELECT p.nama " +
            "FROM transaksi t " +
            "JOIN pelanggan p " +
            "ON t.id_pelanggan = p.id_pelanggan " +
            "WHERE t.id_transaksi = ?";

        PreparedStatement ps =
                conn.prepareStatement(sql);

        ps.setString(1,
                txtIdTransaksi.getText());

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {

            namaAsli = rs.getString("nama");

        } else {

            namaAsli = "Tidak ditemukan";
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                "Error ambil nama : "
                + e.getMessage()
        );
    }
}
private void cetakNotaJasper() {

    try {

        Connection conn = koneksi.getKoneksi();

        HashMap<String, Object> parameter =
                new HashMap<>();

        parameter.put(
                "ID_PEMBAYARAN",
                txtIdPembayaran.getText()
        );

        JasperPrint jp =
                JasperFillManager.fillReport(
                        "src/laporan/laporanNota.jasper",
                        parameter,
                        conn
                );

        JasperViewer.viewReport(jp, false);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                "Gagal cetak nota : "
                + e.getMessage()
        );
    }
}
    
    private void txtIdTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdTransaksiActionPerformed

    private void txtTotalBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalBayarActionPerformed
        // TODO add your handling code here:
       cbStatus.removeAllItems();
       cbStatus.addItem("Lunas");
       cbStatus.addItem("Belum Lunas");
    }//GEN-LAST:event_txtTotalBayarActionPerformed

    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStatusActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        // TODO add your handling code here:
           try {

        Connection conn = koneksi.getKoneksi();

        String sql =
                "INSERT INTO pembayaran "
                + "(id_pembayaran, tanggal_bayar, "
                + "id_transaksi, total_bayar, status) "
                + "VALUES (?, ?, ?, ?, ?)";

        PreparedStatement ps =
                conn.prepareStatement(sql);

        ps.setString(1, txtIdPembayaran.getText());

        java.sql.Date sqlDate =
                new java.sql.Date(
                        new java.util.Date().getTime()
                );

        ps.setDate(2, sqlDate);

        ps.setString(3, txtIdTransaksi.getText());

        ps.setInt(
                4,
                Integer.parseInt(
                        txtTotalBayar.getText()
                )
        );

        ps.setString(
                5,
                cbStatus.getSelectedItem().toString()
        );

        ps.executeUpdate();

        /* =========================
           CETAK NOTA
        ========================= */
        cetakNotaJasper();

        JOptionPane.showMessageDialog(
                null,
                "Pembayaran berhasil!"
        );

        new Layanan().setVisible(true);

        this.dispose();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                null,
                e.getMessage()
        );
    }
    }//GEN-LAST:event_bsimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bsimpan;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtIdPembayaran;
    private javax.swing.JTextField txtIdTransaksi;
    private javax.swing.JTextField txtTotalBayar;
    // End of variables declaration//GEN-END:variables
}
